In [2]:
import numpy as np

a1 = np.arange(10)
print(a1)
print(a1.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [3]:
a2 = np.arange(0, 30, 3)
print(a2)

[ 0  3  6  9 12 15 18 21 24 27]


In [4]:
a3 = np.zeros(4)
print(a3)

[0. 0. 0. 0.]


In [5]:
a4 = np.zeros((2,3))
print(a4)

[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
a5 = np.full((4,3), 7)
print(a5)

[[7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]]


In [7]:
# identity matrix
a6 = np.eye(4)
print(a6)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
# random
a7 = np.random.random((2,4))
print(a7)

[[0.08998743 0.5194238  0.24114226 0.97641642]
 [0.57788459 0.48831275 0.02501171 0.67894527]]


In [9]:
# array from list
list1 = [1,2,3,4,5]
r1 = np.array(list1)
print(r1)

[1 2 3 4 5]


In [10]:
# accessing arrays
print(a7[0,1])

0.5194238025885434


In [11]:
# 2d shape
print(a7.shape)

(2, 4)


In [12]:
list2 = [6,7,8,9,0]
r2 = np.array([list1, list2])

In [13]:
# boolean indexing
print(r1<2)

[ True False False False False]


In [15]:
print(r1[r1>2])

[3 4 5]


In [17]:
# boolean indexing example
nums = np.arange(20)
print(nums)

odds = nums[nums % 2 == 1]
print(odds)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


In [24]:
import numpy as np

a = np.array([[1,2,3,4,5],
              [4,5,6,7,8],
              [9,8,7,6,5]])
print(a)

[[1 2 3 4 5]
 [4 5 6 7 8]
 [9 8 7 6 5]]


In [3]:
# slicing arrays
b1 = a[1:3, :3]
print(b1)

[[4 5 6]
 [9 8 7]]


In [4]:
btest = a[0:2, :4]
print(btest)

[[1 2 3 4]
 [4 5 6 7]]


In [5]:
btest2 = a[0:3, 1:3]
print(btest2)

[[2 3]
 [5 6]
 [8 7]]


In [6]:
b2 = a[-2:,-2:]
print(b2)

[[7 8]
 [6 5]]


In [7]:
# this is a reference of the original array, not a copy
b3 = a[1:,2:]
print(b3)

[[6 7 8]
 [7 6 5]]


In [10]:
b4 = a[2:,:]
print(b4)
print(b4.shape)

[[9 8 7 6 5]]
(1, 5)


In [11]:
b5 = a[2,:]
print(b5)
print(b5.shape)

[9 8 7 6 5]
(5,)


In [13]:
# reshaping
b5 = b5.reshape(1,-1)
print(b5)

# -1 lets the method decide what to reshape it to
# see .flatten() (copy) or .ravel() (reference)

[[9 8 7 6 5]]


In [14]:
# vector addition
x1 = np.array([[1,2,3],[4,5,6]])
y1 = np.array([[7,8,9],[2,3,4]])
print(x1 + y1)
# or np.add(x1,y1)

[[ 8 10 12]
 [ 6  8 10]]


In [15]:
print(np.subtract(x1,y1))
print(np.multiply(x1,y1))
print(np.divide(x1,y1))

[[-6 -6 -6]
 [ 2  2  2]]
[[ 7 16 27]
 [ 8 15 24]]
[[0.14285714 0.25       0.33333333]
 [2.         1.66666667 1.5       ]]


In [17]:
# scalar / dot product
x = np.array([2,3])
y = np.array([4,2])
np.dot(x,y)

14

In [20]:
# matrix multiplication
x2 = np.array([[1,2,3],[4,5,6]])
y2 = np.array([[7,8],[9,10],[11,12]])
print(np.dot(x2,y2))

[[ 58  64]
 [139 154]]


In [22]:
# matrix class - 2d only
# subclass of ndarray
x3 = np.matrix([[1,2],[4,5]])
y3 = np.matrix([[7,8],[2,3]])
# convert array to matrix with asmatrix()
print(x3*y3)

[[11 14]
 [38 47]]


In [28]:
# cumulative sum
atest = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(atest.cumsum())
print(atest.cumsum(axis=0))
print(atest.cumsum(axis=1))

[ 1  3  6 10 15 21 28 36 45]
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


In [30]:
# sorting
ages = np.array([34,12,37,5,13])
sorted_ages = np.sort(ages)
print(sorted_ages)

[ 5 12 13 34 37]


In [31]:
# sort original array
ages.sort()
print(ages)

[ 5 12 13 34 37]


In [32]:
ages = np.array([34,12,37,5,13])
print(ages.argsort())

[3 1 4 0 2]


In [34]:
print(ages[ages.argsort()])

[ 5 12 13 34 37]


In [35]:
# argsort example
persons = np.array(['John','Mary','Peter','Will','Joe'])
ages = np.array([34,12,37,5,13])
heights = np.array([1.76,1.2,1.68,0.5,1.25])

sort_indicies = np.argsort(ages)
print(persons[sort_indicies])
print(ages[sort_indicies])
print(heights[sort_indicies])

['Will' 'Mary' 'Joe' 'John' 'Peter']
[ 5 12 13 34 37]
[0.5  1.2  1.25 1.76 1.68]


In [39]:
# can sort based on names as well with np.argsort(persons)
# and can sort reverse order as well
sort_indicies_reverse = np.argsort(persons)[::-1]
print(persons[sort_indicies_reverse])

['Will' 'Peter' 'Mary' 'John' 'Joe']


In [40]:
# array assignment
list1 = [[1,2,3,4],[5,6,7,8]]
a1 = np.array(list1)
print(a1)

[[1 2 3 4]
 [5 6 7 8]]


In [46]:
a2 = a1
print(a2)

[[11  2  3  4  5  6  7  8]]


In [43]:
a2[0][0] = 1
print(a1)
print(list1)

[[11  2  3  4]
 [ 5  6  7  8]]
[[1, 2, 3, 4], [5, 6, 7, 8]]


In [45]:
# remember -1 auto-resizes here
a1.shape = 1,-1
print(a1)
print(a2)

[[11  2  3  4  5  6  7  8]]
[[11  2  3  4  5  6  7  8]]


In [57]:
# copy by view (shallow copy)
a1[0][0] = 11
a1.shape = 2,4
a2 = a1.view()
print(a1)
print(a2)

[[11  2  3  4]
 [ 5  6  7  8]]
[[11  2  3  4]
 [ 5  6  7  8]]


In [59]:
a1.shape = 1,-1
print(a1)
print(a2)

[[11  2  3  4  5  6  7  8]]
[[11  2  3  4]
 [ 5  6  7  8]]


In [60]:
# copying by value (deep copy)
a1 = np.array(list1)
a2 = a1.copy()

a1[0][0] = 111
print(a1)
print(a2)

a1.shape = 1,-1
print(a1)
print(a2)

[[111   2   3   4]
 [  5   6   7   8]]
[[1 2 3 4]
 [5 6 7 8]]
[[111   2   3   4   5   6   7   8]]
[[1 2 3 4]
 [5 6 7 8]]
